# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, choices=[('CITE', 'College of information and Technology  '), ('CBA', 'College Busnisss And Accountancy'), ('ASCEND', 'ASCEND ')], default='b', help_text='Department', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(help_text='Enter your Last_name ', max_length=100)),
                ('First_name', models.CharField(help_text='Enter your First name ', max_length=200)),
                ('MI', models.CharField(help_text='Enter your Middle Name', max_length=200)),
                ('Sex', models.CharField(blank=True, choices=[('m', 'Male'), ('F', 'Female')], default='m', max_length=1)),
            ],
        ),
    ]
