# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=150)),
                ('Course_Discription', models.CharField(max_length=250)),
            ],
        ),
    ]
